### ISSUE TITLE
 oci_logging_unified_agent_configuration throws error 409, conflict or SIGSEGV segmentation violation

### ISSUE THREAD

**Issue by trondstromme** [oracle/terraform-provider-oci#1473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/oci v4.49.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

oci_logging_unified_agent_configuration

### Terraform Configuration Files

```
resource "oci_logging_log" "os_audit" {
  display_name = "${local.system}-${local.env_name}-os-audit-log"
  log_group_id = oci_logging_log_group.os_audit.id
  log_type     = "CUSTOM"
}

resource "oci_logging_log_group" "os_audit" {
  compartment_id = local.compartment
  display_name   = "${local.system}-${local.env_name}-os-audit-loggr"

  defined_tags = {
    "operations.system"    = local.system
    "operations.env"       = local.env_name
    "operations.component" = "os"
    "operations.type"      = "loggr"
    "operations.index"     = "1"
  }
}

resource "oci_logging_unified_agent_configuration" "os_audit" {
  compartment_id = local.compartment
  display_name   = "${local.system}-${local.env_name}-os-audit-uag"
  is_enabled     = true
  description    = "audit log"

  group_association {
    group_list = [data.oci_identity_dynamic_groups.test_log_dg.id, ]
  }

  service_configuration {
    configuration_type = "LOGGING"

    destination {
      log_object_id = oci_logging_log.os_audit.id
    }
    sources {
      channels = []
      name = "audit_input_name"
      source_type = "LOG_TAIL"
      paths       = ["/var/log/audit/audit.log", ]

      # parser {
      #   parser_type = "SYSLOG"
      # }
    }
  }
}
```

### Expected Behavior

log, log group and agent configuration should be created

### Actual Behavior

on initial run, returned:
```
╷
│ Error: 409-Conflict
│ Provider version: 4.49.0, released on 2021-10-20.
│ Service: Logging Unified Agent Configuration
│ Error Message: DuplicateKeyException. Configuration already exists
│ OPC request ID: 6763bf72b5b185ed6402dac136b94fe9/46F399E7F19CD9D420C69637725C7D83/1278CA4148E8C8155D7EA021B22B987A
│ Suggestion: The resource is in a conflicted state. Please retry again or contact support for help with service: Logging Unified Agent Configuration
│
│
│   with oci_logging_unified_agent_configuration.os_audit,
│   on logging.tf line 59, in resource "oci_logging_unified_agent_configuration" "os_audit":
│   59: resource "oci_logging_unified_agent_configuration" "os_audit" {
│
```
then deleted agent configuration
on second run

```

oci_logging_unified_agent_configuration.os_audit: Creating...
oci_logging_unified_agent_configuration.os_audit: Still creating... [10s elapsed]
oci_logging_unified_agent_configuration.os_audit: Still creating... [20s elapsed]
╷
│ Error: Plugin did not respond
│
│   with oci_logging_unified_agent_configuration.os_audit,
│   on logging.tf line 57, in resource "oci_logging_unified_agent_configuration" "os_audit":
│   57: resource "oci_logging_unified_agent_configuration" "os_audit" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-oci_v4.49.0_x4 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2f04fa9]

goroutine 82 [running]:
github.com/terraform-providers/terraform-provider-oci/oci.(*LoggingUnifiedAgentConfigurationResourceCrud).ID(0xc001283170, 0x3d83fc0, 0xc001283170)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/logging_unified_agent_configuration_resource.go:439 +0x9
github.com/terraform-providers/terraform-provider-oci/oci.getResourceOCID(...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/errors.go:191
github.com/terraform-providers/terraform-provider-oci/oci.newCustomError(0x3d83fc0, 0xc001283170, 0x43b7b80, 0xc001928760, 0x0, 0x40d800)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/errors.go:76 +0x7b2
github.com/terraform-providers/terraform-provider-oci/oci.handleError(...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/errors.go:150
github.com/terraform-providers/terraform-provider-oci/oci.CreateResource(0xc001e05b90, 0x446e3e0, 0xc001283170, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/crud_helpers.go:341 +0xe9
github.com/terraform-providers/terraform-provider-oci/oci.createLoggingUnifiedAgentConfiguration(0xc001e05b90, 0x3e98960, 0xc00198c740, 0x2, 0x5ed1800)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/logging_unified_agent_configuration_resource.go:403 +0xee
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000f01400, 0xc000666780, 0xc000654900, 0x3e98960, 0xc00198c740, 0x371ab01, 0xc001011a48, 0xc001275a40)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:320 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0000c8100, 0xc0019d9a38, 0xc000666780, 0xc000654900, 0xc001272e08, 0xc0013b1d20, 0x3768020)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000f120, 0x4469ae0, 0xc00123b7d0, 0xc001e055e0, 0xc00000f120, 0xc00123b7d0, 0xc001f96ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:895 +0x8ab
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x3d3d0a0, 0xc00000f120, 0x4469ae0, 0xc00123b7d0, 0xc001f89800, 0x0, 0x4469ae0, 0xc00123b7d0, 0xc000234600, 0x599)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00038d500, 0x447d6c0, 0xc000103080, 0xc0003dc300, 0xc00035ec60, 0x5e878e0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/google.golang.org/grpc/server.go:1194 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc00038d500, 0x447d6c0, 0xc000103080, 0xc0003dc300, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/google.golang.org/grpc/server.go:1517 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000660c20, 0xc00038d500, 0x447d6c0, 0xc000103080, 0xc0003dc300)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/google.golang.org/grpc/server.go:859 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/google.golang.org/grpc/server.go:857 +0x1fd

Error: The terraform-provider-oci_v4.49.0_x4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

```
[root@REDACTED unified-monitoring-agent]# systemctl status unified-monitoring-agent
● unified-monitoring-agent.service - unified-monitoring-agent: Fluentd based data collector for Oracle Cloud Infrastructure
   Loaded: loaded (/usr/lib/systemd/system/unified-monitoring-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2021-10-25 12:32:29 UTC; 59min ago
     Docs: https://docs.cloud.oracle.com/
  Process: 5093 ExecStart=/opt/unified-monitoring-agent/embedded/bin/fluentd --log /var/log/unified-monitoring-agent/unified-monitoring-agent.log --daemon /var/run/unified-monitoring-agent/unified-monitoring-agent.pid --log-rotate-size 1048576 --log-rotate-age 10 $EXTRA_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 6338 (fluentd)
   Memory: 66.2M (limit: 5.0G)
   CGroup: /system.slice/unified-monitoring-agent.service
           ├─6338 /opt/unified-monitoring-agent/embedded/bin/ruby /opt/unified-monitoring-agent/embedded/bin/fluentd --log /var/log/unified-monitoring-agent/unified-monitoring-agent.log --daemon /var/run/unified-monitoring-agent/unifi...
           └─6343 /opt/unified-monitoring-agent/embedded/bin/ruby -Eascii-8bit:ascii-8bit /opt/unified-monitoring-agent/embedded/bin/fluentd --log /var/log/unified-monitoring-agent/unified-monitoring-agent.log --daemon /var/run/unifie...

Oct 25 12:32:25 REDACTED.domain.no systemd[1]: Starting unified-monitoring-agent: Fluentd based data collector for Oracle Cloud Infrastructure...
Oct 25 12:32:29 REDACTED.domain.no systemd[1]: Started unified-monitoring-agent: Fluentd based data collector for Oracle Cloud Infrastructure.
```
```
[root@REDACTED unified-monitoring-agent]# cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9
```

**Comment by jhult** [comment]
We also just bumped into this with `v4.51.0_x4`:

```
 Error: Plugin did not respond12:26:53  │12:26:53  │... in resource "oci_logging_log" "these":
12:26:53  │   10: resource "oci_logging_log" "these" {12:26:53  │12:26:53  │ The plugin encountered an error, and failed to respond to the
12:26:53  │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
12:26:53  │ contain more details.
12:26:53  ╵12:26:53 12:26:53  Stack trace from the terraform-provider-oci_v4.51.0_x4 plugin:
12:26:53 12:26:53  panic: runtime error: invalid memory address or nil pointer dereference
12:26:53  [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x3157c46]
12:26:53 12:26:53  goroutine 674 [running]:
12:26:53  github.com/terraform-providers/terraform-provider-oci/oci.(*LoggingLogResourceCrud).ID(0xc00200a090, 0x4052380, 0xc00200a090)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/logging_log_resource.go:207 +0x26
12:26:53  github.com/terraform-providers/terraform-provider-oci/oci.getResourceOCID(...)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/errors.go:191
12:26:53  github.com/terraform-providers/terraform-provider-oci/oci.newCustomError(0x4052380, 0xc00200a090, 0x473f3c0, 0xc00186eb00, 0x0, 0x40d800)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/errors.go:76 +0x7b2
12:26:53  github.com/terraform-providers/terraform-provider-oci/oci.handleError(...)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/errors.go:150
12:26:53  github.com/terraform-providers/terraform-provider-oci/oci.CreateResource(0xc001e071f0, 0x47ff1a0, 0xc00200a090, 0x0, 0x0)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/crud_helpers.go:341 +0xe9
12:26:53  github.com/terraform-providers/terraform-provider-oci/oci.createLoggingLog(0xc001e071f0, 0x41ea500, 0xc001da8160, 0x2, 0x63ebc40)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/oci/logging_log_resource.go:171 +0xee
12:26:53  github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000f32f00, 0xc001ef9040, 0xc001a5ac40, 0x41ea500, 0xc001da8160, 0x39ea201, 0xc001f9ea98, 0xc001fd90b0)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:320 +0x375
12:26:53  github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000364380, 0xc002349a38, 0xc001ef9040, 0xc001a5ac40, 0xc001fcf948, 0xc001fc63c0, 0x3a3cd20)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
12:26:53  github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000f420, 0x47fa560, 0xc001fbe9f0, 0xc001e06d20, 0xc00000f420, 0xc001fbe9f0, 0xc00202dba0)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:895 +0x8ab
12:26:53  github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x406b840, 0xc00000f420, 0x47fa560, 0xc001fbe9f0, 0xc001d95140, 0x0, 0x47fa560, 0xc001fbe9f0, 0xc001fe4000, 0x535)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
12:26:53  google.golang.org/grpc.(*Server).processUnaryRPC(0xc001232380, 0x480f020, 0xc000001680, 0xc0023bf100, 0xc000acba70, 0x63a1600, 0x0, 0x0, 0x0)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/google.golang.org/grpc/server.go:1194 +0x522
12:26:53  google.golang.org/grpc.(*Server).handleStream(0xc001232380, 0x480f020, 0xc000001680, 0xc0023bf100, 0x0)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/google.golang.org/grpc/server.go:1517 +0xd05
12:26:53  google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000558610, 0xc001232380, 0x480f020, 0xc000001680, 0xc0023bf100)
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/google.golang.org/grpc/server.go:859 +0xa5
12:26:53  created by google.golang.org/grpc.(*Server).serveStreams.func1
12:26:53  	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-oci/vendor/google.golang.org/grpc/server.go:857 +0x1fd
12:26:53 12:26:53  Error: The terraform-provider-oci_v4.51.0_x4 plugin crashed!
12:26:53 12:26:53  This is always indicative of a bug within the plugin. It would be immensely
12:26:53  helpful if you could report the crash with the plugin's maintainers so that it
12:26:53  can be fixed. The output above should help diagnose the issue.
12:26:53
```

**Comment by ravinitp** [comment]
We are very sorry that we couldn't respond to each and every issue reported on GitHub. 
Although we have refined the process to prioritize customer issues on GitHub, since this issue was reported a while ago, there is a good chance it may have been fixed in the latest version of Terraform Provider OCI. 
If you are still experiencing this issue, please create a new issue and label it as Bug.
