### ISSUE TITLE
 Error: The terraform-provider-oci_v5.0.0 plugin crashed!

### ISSUE THREAD

**Issue by Reemayg1999** [oracle/terraform-provider-oci#1889]
please resolve this issue

plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.
Stack trace from the terraform-provider-oci_v5.0.0 plugin:
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 16 [running]:
github.com/oracle/terraform-provider-oci/internal/service/database_management.managedDatabaseHashCodeForSets({0x0?, 0x0?})
	github.com/oracle/terraform-provider-oci/internal/service/database_management/database_management_managed_database_group_resource.go:117 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0x44e949?, {0x0?, 0x0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/set.go:251 +0x2c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc00d2f4bc0, {0x0?, 0x0}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/set.go:231 +0x96
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readSet(0xc00db8fc80, {0xc00db87ea0, 0x1, 0x1}, 0x0?)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/field_reader_config.go:284 +0x4b3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).readField(0xc00db8fc80, {0xc00db87ea0?, 0x1, 0x1}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/field_reader_config.go:107 +0x566
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ConfigFieldReader).ReadField(0x5874040?, {0xc00db87ea0?, 0x65a34f5?, 0x6?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/field_reader_config.go:29 +0xbc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MultiLevelFieldReader).ReadFieldExact(0xc00db87e90?, {0xc00db87ea0, 0x1, 0x1}, {0x65a34f5, 0x6})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/field_reader_multi.go:31 +0xa8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0xc00d2e7a00, {0xc00db87ea0, 0x1, 0x1}, 0x0?)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource_data.go:548 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).getChange(0x0?, {0x65cc4eb?, 0x11?}, 0x51?, 0xaf?)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource_data.go:524 +0x1b8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).diffChange(0xc00d2e7a00?, {0x65cc4eb?, 0x1?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource_data.go:501 +0x76
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diffSet(0xc000289468?, {0x65cc4eb, 0x11}, 0xc00d2fcc80, 0xc000289428, {0x6de8da0?, 0xc00d2e7a00?}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:1238 +0x82
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc000289720?, {0x65cc4eb, 0x11}, 0xc00d2fcc80, 0xc00d2f49c0, {0x6de8da0?, 0xc00d2e7a00}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:963 +0x217
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc00db8f560, {0x6dde700, 0xc00d2e99c0}, 0xc00db8a850, 0xc00db8faa0, 0x0, {0x0, 0x0}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/schema.go:522 +0x245
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.diffFromValues({0x6dde700, 0xc00d2e99c0}, {{{0x6de6538?, 0xc004492930?}}, {0x0?, 0x0?}}, {{{0x6de6538, 0xc004492960}}, {0x58fbb80, 0xc00db8f440}}, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/shims.go:39 +0xfe
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.DiffFromValues(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/shims.go:20
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000ca98, {0x6dde700, 0xc00d2e99c0}, 0xc00db944b0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:898 +0x449
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001de9b00, {0x6dde7a8?, 0xc00db8e960?}, 0x0?)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x61ed200?, 0xc001de9b00}, {0x6dde7a8, 0xc00db8e960}, 0xc0047c8ea0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000133dc0, {0x6ded010, 0xc0002de480}, 0xc0046d9d00, 0xc0023e3f20, 0x9eecd60, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc000133dc0, {0x6ded010, 0xc0002de480}, 0xc0046d9d00, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x28a

**Comment by Mistawes** [comment]
I have a ticket open with OCI support for this exact issue. No suggestion for a fix yet.

I've tried all OCI providers from 5.2.1 back to 4.123.0 and they all crash with this same error.

**Comment by Mistawes** [comment]
Sorry for the bump, but OCI still haven't given any meaningful response to the ticket I opened for this over a month ago - even after escalating it.

Our production systems are managed by Terraform and since this issue popped up, we haven't been able to deploy changes.

Their support is appalling and I wouldn't rely on it for my production environment again.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.

**Comment by sagarp337** [comment]
Apologies for the delayed response. Could you please share the configuration code you're using to reproduce or debug the issue? The crash may be caused by an incorrect parameter value in the configuration.
