### ISSUE TITLE
Plugin crashes while creating instance provider v6.12.0

### ISSUE THREAD

**Issue by vinitkapoor** [oracle/terraform-provider-oci#2210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Provider: v6.20.0
TF version: 1.9.3

### Affected Resource(s)

oci_core_instance

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Panic Output

Error: Plugin did not respond

  with module.instances.oci_core_instance.instance[0],
  on .terraform/modules/instances/main.tf line 95, in resource "oci_core_instance" "instance":
  95: resource "oci_core_instance" "instance" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
more details.

Stack trace from the terraform-provider-oci_v6.12.0 plugin:

panic: interface conversion: interface {} is map[string]interface {}, not map[string]map[string]interface {}

goroutine 65 [running]:
github.com/oracle/terraform-provider-oci/internal/service/core.(*CoreInstanceResourceCrud).Update(0xc004008a40)
	github.com/oracle/terraform-provider-oci/internal/service/core/core_instance_resource.go:1511 +0x2119
github.com/oracle/terraform-provider-oci/internal/tfresource.UpdateResource({0x876d4b0, 0xc002d41a00}, {0x86ee240, 0xc004008a40})
	github.com/oracle/terraform-provider-oci/internal/tfresource/crud_helpers.go:359 +0x134
github.com/oracle/terraform-provider-oci/internal/service/core.updateCoreInstance(0xc002d41a00, {0x7dc27a0, 0xc00239cc00})
	github.com/oracle/terraform-provider-oci/internal/service/core/core_instance_resource.go:1039 +0x2ed
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x875ef58?, {0x875ef58?, 0xc002d24cf0?}, 0xd?, {0x7dc27a0?, 0xc00239cc00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:800 +0x15f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0023d4fc0, {0x875ef58, 0xc002d24cf0}, 0xc002d6b6c0, 0xc002d41880, {0x7dc27a0, 0xc00239cc00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:919 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00239c678, {0x875ef58?, 0xc002d24c30?}, 0xc002d183c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1078 +0xd5c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc002c40140, {0x875ef58?, 0xc002d24270?}, 0xc002d42000)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/tf5server/server.go:846 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x7a586c0, 0xc002c40140}, {0x875ef58, 0xc002d24270}, 0xc002d40080, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022ae00, {0x875ef58, 0xc002d241b0}, {0x8773980, 0xc002aa7040}, 0xc002d2a000, 0xc001c3b1a0, 0xca7def8, 0x0)
	google.golang.org/grpc@v1.61.1/server.go:1385 +0xdd1
google.golang.org/grpc.(*Server).handleStream(0xc00022ae00, {0x8773980, 0xc002aa7040}, 0xc002d2a000)
	google.golang.org/grpc@v1.61.1/server.go:1796 +0xfb8
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.61.1/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 50
	google.golang.org/grpc@v1.61.1/server.go:1040 +0x125

### Expected Behavior

Instance should have been crated.

### Actual Behavior

Provider panicked

### Steps to Reproduce

Try to create instance

1. `terraform apply`

### Important Factoids

None

### References

None

**Comment by brandootr** [comment]
This also happens when updating an instance

**Comment by spantaleev** [comment]
It seems like v6.13.0 is also affected. I've tested it with both OpenTofu v1.8.2 and v1.8.3.

v6.11.0 is working fine though, so it appears that the regression was introduced in v6.12.0.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.
