### ISSUE TITLE
 Error: Plugin did not respond

### ISSUE THREAD

**Issue by kendalldavila** [oracle/terraform-provider-oci#2218]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Panic Output
$ terraform init -backend-config="access_key=${TFSTATE_ACCESS_KEY_OCI}" -backend-config="secret_key=${TFSTATE_SECRET_KEY_OCI}" -no-color -input=false
Initializing the backend...
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing modules...
Downloading git::https://gitlab.falabella.tech/fif/core/infraestructura/oci/modules/oracle_exadataDB.git for db_exadata...
- db_exadata in .terraform/modules/db_exadata
Initializing provider plugins...
- Reusing previous version of hashicorp/vault from the dependency lock file
- Reusing previous version of hashicorp/oci from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of oracle/oci from the dependency lock file
- Installing hashicorp/vault v4.4.0...
- Installed hashicorp/vault v4.4.0 (signed by HashiCorp)
- Installing hashicorp/oci v6.13.0...
- Installed hashicorp/oci v6.13.0 (signed by HashiCorp)
- Installing hashicorp/random v3.6.3...
- Installed hashicorp/random v3.6.3 (signed by HashiCorp)
- Installing oracle/oci v6.12.0...
- Installed oracle/oci v6.12.0 (signed by a HashiCorp partner, key ID 1533A49284137CEB)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
Warning: Additional provider information from registry
The remote registry returned warnings for
registry.terraform.io/hashicorp/oci:
- For users on Terraform 0.13 or greater, this provider has moved to
oracle/oci. Please update your source in required_providers.
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
$ export TF_VAR_ssh_public_key=/opt/keys/fif_cl.pub
$ export TF_VAR_ssh_private_key=/opt/keys/fif_cl
$ terraform apply -input=false -auto-approve tfplan
module.db_exadata.oci_database_db_home.db_home: Modifying... [id=ocid1.dbhome.oc1.sa-santiago-1.anzwgljr4oomvbqagjsofpf743ghdaobbcraarq7uhpvsxvlelkzp3e7esm2oq]
╷
│ Error: Plugin did not respond
│ 
│   with module.db_exadata.oci_database_db_home.db_home,
│   on .terraform/modules/db_exadata/dbhome.tf line 24, in resource "oci_database_db_home" "db_home":
│   24: resource "oci_database_db_home" "db_home" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-oci_v6.13.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4dbbd0a]
goroutine 26 [running]:
github.com/oracle/terraform-provider-oci/internal/service/database.(*DatabaseDbHomeResourceCrud).Update(0xc003e3a9c0)
	github.com/oracle/terraform-provider-oci/internal/service/database/database_db_home_resource.go:605 +0x30a
github.com/oracle/terraform-provider-oci/internal/tfresource.UpdateResource({0x87ac0f0, 0xc003dd0800}, {0x873a018, 0xc003e3a9c0})
	github.com/oracle/terraform-provider-oci/internal/tfresource/crud_helpers.go:359 +0x134
github.com/oracle/terraform-provider-oci/internal/service/database.updateDatabaseDbHome(0xc003dd0800, {0x7dfd600, 0xc002b9cd98})
	github.com/oracle/terraform-provider-oci/internal/service/database/database_db_home_resource.go:1560 +0x10c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x879da28?, {0x879da28?, 0xc003dc2c00?}, 0xd?, {0x7dfd600?, 0xc002b9cd98?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:800 +0x15f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0026[142](https://gitlab.falabella.tech/fif/core/infraestructura/oci/databaseoracleexadata/bfa-cl-flx-exa-sascl1-prd-00/-/jobs/36635627#L142)a0, {0x879da28, 0xc003dc2c00}, 0xc003de05b0, 0xc003dd0600, {0x7dfd600, 0xc002b9cd98})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:919 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002b9c678, {0x879da28?, 0xc003dc2b40?}, 0xc003dc0460)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1078 +0xd5c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000142aa0, {0x879da28?, 0xc003dc2180?}, 0xc0002c33b0)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/tf5server/server.go:846 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x7a91d00, 0xc000142aa0}, {0x879da28, 0xc003dc2180}, 0xc002c39b80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000228e00, {0x879da28, 0xc003dc20f0}, {0x87b2600, 0xc002cc0000}, 0xc003da9e60, 0xc002bba7e0, 0xcadaff8, 0x0)
	google.golang.org/grpc@v1.61.1/server.go:1385 +0xdd1
google.golang.org/grpc.(*Server).handleStream(0xc000228e00, {0x87b2600, 0xc002cc0000}, 0xc003da9e60)
	google.golang.org/grpc@v1.61.1/server.go:1796 +0xfb8
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.61.1/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 55
	google.golang.org/grpc@v1.61.1/server.go:1040 +0x125
Error: The terraform-provider-oci_v6.13.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: command terminated with exit code 1

### Steps to Reproduce

1. `terraform apply`

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We observed the affected resources are not provided in the description or it's incorrect. We request you to add it in issue description as mentioned in below format.
Example: affected_resources = oci_core_instance , oci_core_instances
 
If it's not related to any particular resource then mention affected resource as terraform.
Example: affected_resources = terraform
 
As this works through automation, request you to follow exact syntax.

**Comment by kendalldavila** [comment]
Please we need a prompt response, review and solution to the reported bug, this affects a new implementation in the production environment

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.
