### ISSUE TITLE
panic: github.com/oracle/terraform-provider-oci/internal/service/load_balancer 

### ISSUE THREAD

**Issue by hrez** [oracle/terraform-provider-oci#2251]
This happens when oci loadbalancer fails to be created and remains in "failed" state. 
On terraform run after that it panics.

module.oci_lb.data.oci_load_balancer_protocols.this: Reading...
module.oci_lb.data.oci_load_balancer_policies.this: Reading...
module.oci_lb.data.oci_identity_availability_domains.this: Reading...
module.oci_lb.data.oci_load_balancer_shapes.this: Reading...
module.oci_lb.data.oci_load_balancer_protocols.this: Read complete after 0s [id=LoadBalancerLoadBalancerProtocolsDataSource-572408765]
module.oci_lb.data.oci_identity_availability_domains.this: Read complete after 0s [id=IdentityAvailabilityDomainsDataSource-572408765]
module.oci_lb.data.oci_load_balancer_shapes.this: Read complete after 0s [id=LoadBalancerLoadBalancerShapesDataSource-572408765]
module.oci_lb.oci_load_balancer_load_balancer.this[0]: Refreshing state... [id=ocid1.loadbalancer.oc1.us-sanjose-1.aaaaaaaazjlrk2gluo5xheb3dajluckbw5dz5t4qfrt5wmuf5unonuaqcvqq]
module.oci_lb.data.oci_load_balancer_policies.this: Read complete after 0s [id=LoadBalancerLoadBalancerPoliciesDataSource-572408765]
╷
│ Error: Plugin did not respond
│
│   with module.oci_lb.oci_load_balancer_load_balancer.this[0],
│   on ../terraform-oci-tdf-lb/main.tf line 22, in resource "oci_load_balancer_load_balancer" "this":
│   22: resource "oci_load_balancer_load_balancer" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-oci_v6.19.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46c73a2]

goroutine 122 [running]:
github.com/oracle/terraform-provider-oci/internal/service/load_balancer.(*LoadBalancerLoadBalancerResourceCrud).SetData(0xc003f43230)
        github.com/oracle/terraform-provider-oci/internal/service/load_balancer/load_balancer_load_balancer_resource.go:613 +0x262
github.com/oracle/terraform-provider-oci/internal/tfresource.ReadResource({0x8925948, 0xc003f43230})
        github.com/oracle/terraform-provider-oci/internal/tfresource/crud_helpers.go:325 +0x128
github.com/oracle/terraform-provider-oci/internal/service/load_balancer.readLoadBalancerLoadBalancer(0xc003991100, {0x7fc2400, 0xc002e02528})
        github.com/oracle/terraform-provider-oci/internal/service/load_balancer/load_balancer_load_balancer_resource.go:223 +0xd7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x8995bf8?, {0x8995bf8?, 0xc003f27b00?}, 0xd?, {0x7fc2400?, 0xc002e02528?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:783 +0x15f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc002a55a40, {0x8995bf8, 0xc003f27b00}, 0xc0039b1c70, {0x7fc2400, 0xc002e02528})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1089 +0x529
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc002d1af30, {0x8995bf8?, 0xc003f27a40?}, 0xc00398ae40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:667 +0x4aa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc002c821e0, {0x8995bf8?, 0xc003f270b0?}, 0xc00399f560)
        github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/tf5server/server.go:775 +0x4c3
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x7c42a00, 0xc002c821e0}, {0x8995bf8, 0xc003f270b0}, 0xc003990b80, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000222c00, {0x8995bf8, 0xc003f27020}, {0x89aa100, 0xc0024a1860}, 0xc003f3aa20, 0xc002d2cd20, 0xcdd3ae8, 0x0)
        google.golang.org/grpc@v1.61.1/server.go:1385 +0xdd1
google.golang.org/grpc.(*Server).handleStream(0xc000222c00, {0x89aa100, 0xc0024a1860}, 0xc003f3aa20)
        google.golang.org/grpc@v1.61.1/server.go:1796 +0xfb8
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.61.1/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 65
        google.golang.org/grpc@v1.61.1/server.go:1040 +0x125

Error: The terraform-provider-oci_v6.19.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We observed the affected resources are not provided in the description or it's incorrect. We request you to add it in issue description as mentioned in below format.
Example: affected_resources = oci_core_instance , oci_core_instances
 
If it's not related to any particular resource then mention affected resource as terraform.
Example: affected_resources = terraform
 
As this works through automation, request you to follow exact syntax.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We observed the affected resources are not provided in the description or it's incorrect. We request you to add it in issue description as mentioned in below format.
Example: affected_resources = oci_core_instance , oci_core_instances
 
If it's not related to any particular resource then mention affected resource as terraform.
Example: affected_resources = terraform
 
As this works through automation, request you to follow exact syntax.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We observed the affected resources are not provided in the description or it's incorrect. We request you to add it in issue description as mentioned in below format.
Example: affected_resources = oci_core_instance , oci_core_instances
 
If it's not related to any particular resource then mention affected resource as terraform.
Example: affected_resources = terraform
 
As this works through automation, request you to follow exact syntax.

**Comment by tf-oci-pub** [comment]
Thank you for reporting the issue. We have raised an internal ticket to track this. Our service engineers will get back to you.
