### ISSUE TITLE
terraform plan fails while creating a database system with oci-provider-2.0.4

### ISSUE THREAD

**Issue by danielguenther1** [oracle/terraform-provider-oci#359]
### Terraform Version

<details>
Terraform v0.10.8
</details>

### OCI Provider Version

<details>
2017/11/11 19:51:49 [INFO] terraform-provider-oci 2.0.4
</details>

### Description:
terraform apply fails while creating a database system. terraform plan runs successfully.
The error occurs since terraform-provider-oci 2.0.3.

Here is the complete error stack:
Error: Error applying plan:

1 error(s) occurred:

* oci_database_db_system.DB1: 1 error(s) occurred:

* oci_database_db_system.DB1: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

panic: interface conversion: interface {} is nil, not string
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4:
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4: goroutine 28 [running]:
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4: main.(*DBSystemResourceCrud).Create(0xc420103d40, 0x18, 0xaf7100)
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4:      /Users/kohashim/projects/go/src/github.com/oracle/terraform-provider-oci/resource_obmcs_database_db_system.go:310 +0x1474
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4: github.com/oracle/terraform-provider-oci/crud.CreateDBSystemResource(0xc420088850, 0xf65580, 0xc420103d40, 0xb72400, 0xbb6501)
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4:      /Users/kohashim/projects/go/src/github.com/oracle/terraform-provider-oci/crud/helpers.go:176 +0x49
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4: main.createDBSystem(0xc420088850, 0xa60c40, 0xc4203cb0a0, 0x0, 0xc4201f4bc8)
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4:      /Users/kohashim/projects/go/src/github.com/oracle/terraform-provider-oci/resource_obmcs_database_db_system.go:253 +0x98
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4: github.com/oracle/terraform-provider-oci/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc42050d920, 0xc42006cc30, 0xc420103c20, 0xa60c40, 0xc4203cb0a0, 0x1, 0xc420187230, 0xc420187230)
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4:      /Users/kohashim/projects/go/src/github.com/oracle/terraform-provider-oci/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x3fd
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4: github.com/oracle/terraform-provider-oci/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4202f8000, 0xc42006c910, 0xc42006cc30, 0xc420103c20, 0x7f669f5ef6c8, 0x0, 0x18)
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4:      /Users/kohashim/projects/go/src/github.com/oracle/terraform-provider-oci/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0xa4
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4: github.com/oracle/terraform-provider-oci/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4202f4020, 0xc4201034a0, 0xc4202f15e0, 0x0, 0x0)
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4:      /Users/kohashim/projects/go/src/github.com/oracle/terraform-provider-oci/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4: reflect.Value.call(0xc42005d440, 0xc42000c008, 0x13, 0xb8be36, 0x4, 0xc420243f20, 0x3, 0x3, 0xc4200a56d8, 0x43a01f, ...)
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4:      /usr/local/go/src/reflect/value.go:434 +0x906
2017-11-11T20:23:24.084+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4: reflect.Value.Call(0xc42005d440, 0xc42000c008, 0x13, 0xc4200a5720, 0x3, 0x3, 0x0, 0x0, 0x0)
2017-11-11T20:23:24.085+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4:      /usr/local/go/src/reflect/value.go:302 +0xa4
2017-11-11T20:23:24.085+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4: net/rpc.(*service).call(0xc420058180, 0xc42006c140, 0xc420014130, 0xc4201f0180, 0xc4202f4740, 0xa5d040, 0xc4201034a0, 0x16, 0xa5d080, 0xc4202f15e0, ...)
2017-11-11T20:23:24.085+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4:      /usr/local/go/src/net/rpc/server.go:381 +0x142
2017-11-11T20:23:24.085+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4: created by net/rpc.(*Server).ServeCodec
2017-11-11T20:23:24.085+0100 [DEBUG] plugin.terraform-provider-oci_v2.0.4:      /usr/local/go/src/net/rpc/server.go:475 +0x36b
2017/11/11 20:23:24 [TRACE] root: eval: *terraform.EvalWriteState
2017-11-11T20:23:24.086+0100 [DEBUG] plugin: plugin process exited: path=/home/z8u2kxk/.terraform.d/plugins/terraform-provider-oci_v2.0.4
2017/11/11 20:23:24 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2017/11/11 20:23:24 [TRACE] root: eval: *terraform.EvalIf
2017/11/11 20:23:24 [TRACE] root: eval: *terraform.EvalWriteState
2017/11/11 20:23:24 [TRACE] root: eval: *terraform.EvalWriteDiff
2017/11/11 20:23:24 [TRACE] root: eval: *terraform.EvalApplyPost
2017/11/11 20:23:24 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* oci_database_db_system.DB1: unexpected EOF
2017/11/11 20:23:24 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* oci_database_db_system.DB1: unexpected EOF
2017/11/11 20:23:24 [TRACE] [walkApply] Exiting eval tree: oci_database_db_system.DB1
2017/11/11 20:23:24 [TRACE] dag/walk: upstream errored, not walking "provider.oci (close)"
2017/11/11 20:23:24 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/11/11 20:23:24 [TRACE] dag/walk: upstream errored, not walking "root"
2017/11/11 20:23:24 [TRACE] Preserving existing state lineage "10c2809f-26bc-4d71-99d5-c941d6bac1ed"
2017/11/11 20:23:24 [TRACE] Preserving existing state lineage "10c2809f-26bc-4d71-99d5-c941d6bac1ed"
2017/11/11 20:23:24 [TRACE] Preserving existing state lineage "10c2809f-26bc-4d71-99d5-c941d6bac1ed"
2017/11/11 20:23:24 [TRACE] Preserving existing state lineage "10c2809f-26bc-4d71-99d5-c941d6bac1ed"
2017/11/11 20:23:24 [DEBUG] plugin: waiting for all plugin processes to complete...
2017-11-11T20:23:24.180+0100 [WARN ] plugin: error closing client during Kill: err="connection is shut down"

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Terraform Plan

<details>
provider "oci" {
  tenancy_ocid = "${var.tenancy_ocid}"
  user_ocid    = "${var.user_ocid}"
  fingerprint  = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
  private_key_password = "${var.private_key_password}"
  region       = "us-ashburn-1"
}

### DB ###

resource "oci_database_db_system" "DB1" {
  availability_domain = "EeHu:US-ASHBURN-AD-1"
  compartment_id = "ocid1.compartment.oc1..aaaaaaaanpinocd5wrshkfhnwj5yoidryhwmpsmx6jxvb2yxg25l4hh7a6ja"
  cpu_core_count = "8"
  database_edition = "ENTERPRISE_EDITION_EXTREME_PERFORMANCE"
  db_home {
    database {
      "admin_password" = "Test-Adm#2017"
      "db_name" = "CDBTST1"
      "character_set" = "AL32UTF8"
      "ncharacter_set" = "AL16UTF16"
      "db_workload" = "DSS"
      "pdb_name" = "PDBREPO1"
    }
    db_version = "12.1.0.2"
    display_name = "DB1-TEST"
  }
  disk_redundancy = "HIGH"
  shape = "BM.DenseIO1.36"
  subnet_id = "ocid1.subnet.oc1.iad.aaaaaaaacbsgr4cdczojgcfw5hb2ztuaj5rwbu3au5fbruliyennij4sdvdq"
  backup_subnet_id = "ocid1.subnet.oc1.iad.aaaaaaaacbsgr4cdczojgcfw5hb2ztuaj5rwbu3au5fbruliyennij4sdvdq"
  ssh_public_keys = [ "${split("\n", file("/home/z8u2kxk/cloud/ssh_keys/all_id_rsa.pub"))}" ]
  cluster_name = "vl008-u6"
  display_name = "DB1"
  domain = "srv.allianz"
  hostname = "vl008-u6"
  data_storage_percentage = "80"
  data_storage_size_in_gb = "4096"
  #license_model = "BRING_YOUR_OWN_LICENSE"
  #node_count = "2"
  timeouts {
     create = "120m"
   }
}

</details>

**Comment by kohashim** [comment]
Thank you for the report.  I was able to reproduce the issue.  Looks like this issue is caused by the 'split' built-in function in the line:
`ssh_public_keys = [ "${split("\n", file("/home/z8u2kxk/cloud/ssh_keys/all_id_rsa.pub"))}" ]`

I bet you are seeing inconsistency between the value of "ssh_public_keys.#" and the number of ssh_public_keys parameters for "oci_database_db_system.DB1" in the output from "terraform plan".  Let's say your "all_id_rsa.pub" contains 1 actual string line and 3 newlines such as "ABC\n\n\n", then "terraform plan" says "ssh_public_keys.#" = 4 and only "ssh_publc_keys.0" = "ABC".  Looks like in this case the 'split' built-in function produces 4 string objects: "ABC", nil, nil, and nil.  That's why the panic occurs.

I would say this is a bug in the 'split' built-in function producing nil instead of an empty string unless that's the intended behavior of 'split'.  I would also say this is potentially a bug in the schema validation of Terraform, because terraform-provider-oci clearly defines that "ssh_public_keys" is an array of strings while Terraform somehow lets an array including nil pass their validation.

In the meantime, I would suggest you may want to carefully remove extra newlines in your "all_id_rsa.pub" or use an alternative way to specify multiple public keys.

**Comment by kohashim** [comment]
Found a workaround using the 'compact' built-in function in https://github.com/hashicorp/terraform/issues/12472 as follows:
`ssh_public_keys = [ "${compact(split("\n", file("/home/z8u2kxk/cloud/ssh_keys/all_id_rsa.pub")))}" ]`

**Comment by kohashim** [comment]
An issue for the bug in 'split' has already been opened in Terraform: https://github.com/hashicorp/terraform/issues/16220

**Comment by danielguenther1** [comment]
Thanks a lot not only for finding out the root cause but in addition to find a workaround. I've modified my Terraform script and is working now.
